### ISSUE TITLE
Exclude DS_Store

### ISSUE THREAD

**Issue by tyonirwansyah** [AirFusion45/db8bot#306]
Hello there, I just ran into your repository. I like the features that you added in the commands. I suggest you should ignore the .DS_Store file in all your directories. Its polluting the directories and does not provide any use for non Mac OS users. If you are free you should start excluding the file.

Thank you, have a nice day.

**Comment by AirFusion45** [comment]
DS_Store has been removed in the newest branch. Changes will be deployed when v4 releases (~1-2 months due to oauth2 scope migration).

Issue closed.
